server:
  port: 9411
spring:
#  cloud:
#    consul:
#      discovery:
#        health-check-path: /actuator/health
#        health-check-interval: 10s
#        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#        service-name: ${spring.application.name}
#      host: localhost
#      port: 8500

  application:
    name: zipkin-server


management:
  metrics:
    web:
      server:
        auto-time-requests: false

